import { describe, expect, it } from 'vitest'

import type { ConstructionArtifactReplayResponse } from './types'

describe('ConstructionArtifactReplayResponse turnover diagnostics contract', () => {
  it('accepts backend-shipped turnover_diagnostics_v1.symbol_contributions', () => {
    const response = {
      construction_artifact_id: 'artifact-123',
      truth_separation: {
        baseline_truth: 'imported_portfolio_snapshot',
        candidate_truth: 'hypothetical_construction_artifact',
        candidate_applied: false,
        consumption_mode: 'explicit_reference_only',
      },
      replay_provenance: {
        source: 'construction_artifact_reference',
        construction_artifact_id: 'artifact-123',
        policy_id: 'policy-1',
        policy_definition_id: 'policy-def-1',
        ranked_universe_artifact_id: 'ranked-1',
        ranking_id: 'ranking-1',
        ranking_methodology_id: 'method-1',
        current_portfolio_artifact_id: 'portfolio-1',
        hard_constraints: {
          full_investment: true,
          long_only: true,
          eligible_ranked_universe_only: true,
          max_position_weight: 0.6,
          min_position_weight: null,
          max_turnover_weight: 0.3,
          max_trade_intent_count: 2,
        },
        baseline_input_source: 'normalized_inputs.current_portfolio_weights',
        candidate_input_source: 'final_target_weights',
        selection_rule_trace: {
          rule_ids: ['rule-1'],
          steps: [
            {
              rule_id: 'rule-1',
              rule_order: 1,
              input_candidate_symbols: ['AAPL'],
              output_candidate_symbols: ['MSFT'],
            },
          ],
        },
        turnover_diagnostics_status: 'available',
        turnover_diagnostics_v1: {
          diagnostics_version: 'construction_turnover_diagnostics_v1',
          source: 'persisted_construction_artifact',
          diagnostic_truth: 'artifact_backed_hypothetical_construction_diagnostics_only',
          turnover_basis_method_version: 'half_l1_weight_delta_union_v1',
          reported_value_status: 'computed',
          reported_turnover_weight: 0.2,
          inclusion_flags: {
            uses_current_and_target_weight_union: true,
            includes_initiations: true,
            includes_exits: true,
            includes_zero_delta_positions_in_trade_intent_context: true,
            excludes_zero_delta_positions_from_reported_turnover_sum: true,
          },
          trade_intent_context: {
            source_field: 'trade_intents',
            intent_count: 2,
          },
          feasibility_context: {
            artifact_status: 'feasible',
            failure_reasons_field: 'failure_reasons',
            turnover_failure_reason_present: false,
          },
          constraint_context: {
            constraint_id: 'max_turnover_weight',
            requested: true,
            limit_weight: 0.3,
            evaluation_status: 'pass',
          },
          symbol_contributions: [
            {
              symbol: 'AAPL',
              action: 'hold',
              current_weight: 0.5,
              target_weight: 0.5,
              delta_weight: 0,
              absolute_delta_weight: 0,
              turnover_contribution_weight: 0,
              contribution_fraction_of_reported_turnover: 0,
              included_in_reported_turnover: false,
            },
            {
              symbol: 'MSFT',
              action: 'initiate',
              current_weight: 0,
              target_weight: 0.4,
              delta_weight: 0.4,
              absolute_delta_weight: 0.4,
              turnover_contribution_weight: 0.2,
              contribution_fraction_of_reported_turnover: 1,
              included_in_reported_turnover: true,
            },
          ],
        },
        weighting_trace_status: 'unavailable_legacy_artifact',
        weighting_trace_v1: null,
      },
      baseline_weights: [{ symbol: 'AAPL', target_weight: 0.6 }],
      candidate_weights: [{ symbol: 'MSFT', target_weight: 0.6 }],
      effective_replay_params: {
        benchmark_symbol: 'SPY',
        start_date: '2024-01-01',
        end_date: '2024-12-31',
        initial_capital: 100000,
        rebalance_frequency: 'monthly',
        base_currency: 'USD',
        commission_bps: 0,
        slippage_bps: 0,
        drift_tolerance_pct: null,
        price_basis: 'adjusted_close',
        execution_price_field: 'close',
        execution_lag_days: 1,
        symbol_overrides: {},
      },
      replay: {
        methodology: 'm',
        investor_economics_status: { status: 'available', reason: null },
        reference_result: {
          portfolio_name: 'Reference',
          benchmark_symbol: 'SPY',
          start_date: '2024-01-01',
          end_date: '2024-12-31',
          observation_count: 1,
          rebalance_frequency: 'monthly',
          commission_bps: 0,
          slippage_bps: 0,
          drift_tolerance_pct: null,
          assumptions: {
            price_basis: 'adjusted_close',
            execution_price_field: 'close',
            execution_lag_days: 1,
            calendar_policy: 'intersection_common_dates',
            fractional_shares: true,
            long_only: true,
            leverage_allowed: false,
            tax_treatment: 'pre_tax',
            investor_base_currency: 'USD',
          },
          status: 'ok',
          investor_economics_status: { status: 'available', reason: null },
          instrument_metadata: [],
          starting_weights: [],
          ending_weights: [],
          metrics: {
            total_return_pct: 0,
            annualized_return_pct: 0,
            annualized_volatility_pct: 0,
            downside_volatility_pct: 0,
            max_drawdown_pct: 0,
            sharpe_ratio: 0,
            sortino_ratio: 0,
            benchmark_return_pct: 0,
            excess_return_pct: 0,
            tracking_error_pct: 0,
            information_ratio: 0,
            beta_vs_benchmark: 0,
            correlation_vs_benchmark: 0,
            total_turnover_pct: 0,
            turnover_events_count: 0,
            total_cost_paid: 0,
          },
          equity_curve: [],
          rebalance_events: [],
          trades: [],
        },
        candidate_result: {
          portfolio_name: 'Candidate',
          benchmark_symbol: 'SPY',
          start_date: '2024-01-01',
          end_date: '2024-12-31',
          observation_count: 1,
          rebalance_frequency: 'monthly',
          commission_bps: 0,
          slippage_bps: 0,
          drift_tolerance_pct: null,
          assumptions: {
            price_basis: 'adjusted_close',
            execution_price_field: 'close',
            execution_lag_days: 1,
            calendar_policy: 'intersection_common_dates',
            fractional_shares: true,
            long_only: true,
            leverage_allowed: false,
            tax_treatment: 'pre_tax',
            investor_base_currency: 'USD',
          },
          status: 'ok',
          investor_economics_status: { status: 'available', reason: null },
          instrument_metadata: [],
          starting_weights: [],
          ending_weights: [],
          metrics: {
            total_return_pct: 0,
            annualized_return_pct: 0,
            annualized_volatility_pct: 0,
            downside_volatility_pct: 0,
            max_drawdown_pct: 0,
            sharpe_ratio: 0,
            sortino_ratio: 0,
            benchmark_return_pct: 0,
            excess_return_pct: 0,
            tracking_error_pct: 0,
            information_ratio: 0,
            beta_vs_benchmark: 0,
            correlation_vs_benchmark: 0,
            total_turnover_pct: 0,
            turnover_events_count: 0,
            total_cost_paid: 0,
          },
          equity_curve: [],
          rebalance_events: [],
          trades: [],
        },
        comparison: {
          total_return_diff_pct: 0,
          annualized_return_diff_pct: 0,
          benchmark_return_diff_pct: 0,
          annualized_volatility_diff_pct: 0,
          downside_volatility_diff_pct: 0,
          max_drawdown_diff_pct: 0,
          sharpe_diff: 0,
          sortino_diff: 0,
          excess_return_diff_pct: 0,
          tracking_error_diff_pct: 0,
          information_ratio_diff: 0,
          beta_diff: 0,
          correlation_diff: 0,
          total_turnover_diff_pct: 0,
          total_cost_diff: 0,
        },
        reference_diagnostics: null,
        candidate_diagnostics: null,
        diagnostics_comparison: null,
      },
    } satisfies ConstructionArtifactReplayResponse

    expect(response.replay_provenance.turnover_diagnostics_v1?.symbol_contributions).toEqual([
      {
        symbol: 'AAPL',
        action: 'hold',
        current_weight: 0.5,
        target_weight: 0.5,
        delta_weight: 0,
        absolute_delta_weight: 0,
        turnover_contribution_weight: 0,
        contribution_fraction_of_reported_turnover: 0,
        included_in_reported_turnover: false,
      },
      {
        symbol: 'MSFT',
        action: 'initiate',
        current_weight: 0,
        target_weight: 0.4,
        delta_weight: 0.4,
        absolute_delta_weight: 0.4,
        turnover_contribution_weight: 0.2,
        contribution_fraction_of_reported_turnover: 1,
        included_in_reported_turnover: true,
      },
    ])
    expect(response.replay_provenance.hard_constraints.max_trade_intent_count).toBe(2)
  })
})
