import { describe, expect, it } from 'vitest'

import { isBenchmarkTrendTimelineHistoryRow, isBenchmarkTrendTimelineObservationRow, isDataQualityTimelineHistoryRow, isDataQualityTimelineObservationRow } from './types'
import type { ConstructionArtifactReplayResponse, MonitorDefinitionActiveAlertEpisodeInboxResponse, MonitorDefinitionAlertEpisodeHistoryResponse, MonitorDefinitionAlertReviewTimelineHistoryRow, MonitorDefinitionAlertReviewTimelineObservationRow, MonitorDefinitionAlertReviewTimelineResponse, MonitorDefinitionRecoveredAlertReviewQueueResponse } from './types'

describe('ConstructionArtifactReplayResponse turnover diagnostics contract', () => {
  it('accepts backend-shipped turnover_diagnostics_v1.symbol_contributions', () => {
    const response = {
      construction_artifact_id: 'artifact-123',
      truth_separation: {
        baseline_truth: 'imported_portfolio_snapshot',
        candidate_truth: 'hypothetical_construction_artifact',
        candidate_applied: false,
        consumption_mode: 'explicit_reference_only',
      },
      replay_provenance: {
        source: 'construction_artifact_reference',
        construction_artifact_id: 'artifact-123',
        policy_id: 'policy-1',
        policy_definition_id: 'policy-def-1',
        ranked_universe_artifact_id: 'ranked-1',
        ranked_universe_artifact_schema_version: 'etf_ranking_artifact_v1',
        ranking_id: 'ranking-1',
        ranking_methodology_id: 'method-1',
        ranking_as_of_date: '2026-04-23',
        current_portfolio_artifact_id: 'portfolio-1',
        current_portfolio_as_of_timestamp: '2026-04-23T09:30:00Z',
        top_n: 2,
        hard_constraints: {
          full_investment: true,
          long_only: true,
          eligible_ranked_universe_only: true,
          max_position_weight: 0.6,
          min_position_weight: null,
          max_turnover_weight: 0.3,
          max_trade_intent_count: 2,
        },
        baseline_input_source: 'normalized_inputs.current_portfolio_weights',
        candidate_input_source: 'final_target_weights',
        selection_rule_trace: {
          rule_ids: ['rule-1'],
          steps: [
            {
              rule_id: 'rule-1',
              rule_order: 1,
              input_candidate_symbols: ['AAPL'],
              output_candidate_symbols: ['MSFT'],
            },
          ],
        },
        turnover_diagnostics_status: 'available',
        turnover_diagnostics_v1: {
          diagnostics_version: 'construction_turnover_diagnostics_v1',
          source: 'persisted_construction_artifact',
          diagnostic_truth: 'artifact_backed_hypothetical_construction_diagnostics_only',
          turnover_basis_method_version: 'half_l1_weight_delta_union_v1',
          reported_value_status: 'computed',
          reported_turnover_weight: 0.2,
          inclusion_flags: {
            uses_current_and_target_weight_union: true,
            includes_initiations: true,
            includes_exits: true,
            includes_zero_delta_positions_in_trade_intent_context: true,
            excludes_zero_delta_positions_from_reported_turnover_sum: true,
          },
          trade_intent_context: {
            source_field: 'trade_intents',
            intent_count: 2,
          },
          feasibility_context: {
            artifact_status: 'feasible',
            failure_reasons_field: 'failure_reasons',
            turnover_failure_reason_present: false,
          },
          constraint_context: {
            constraint_id: 'max_turnover_weight',
            requested: true,
            limit_weight: 0.3,
            evaluation_status: 'pass',
          },
          symbol_contributions: [
            {
              symbol: 'AAPL',
              action: 'hold',
              current_weight: 0.5,
              target_weight: 0.5,
              delta_weight: 0,
              absolute_delta_weight: 0,
              turnover_contribution_weight: 0,
              contribution_fraction_of_reported_turnover: 0,
              included_in_reported_turnover: false,
            },
            {
              symbol: 'MSFT',
              action: 'initiate',
              current_weight: 0,
              target_weight: 0.4,
              delta_weight: 0.4,
              absolute_delta_weight: 0.4,
              turnover_contribution_weight: 0.2,
              contribution_fraction_of_reported_turnover: 1,
              included_in_reported_turnover: true,
            },
          ],
        },
        weighting_trace_status: 'unavailable_legacy_artifact',
        weighting_trace_v1: null,
      },
      baseline_weights: [{ symbol: 'AAPL', target_weight: 0.6 }],
      candidate_weights: [{ symbol: 'MSFT', target_weight: 0.6 }],
      review_basis: {
        basis_version: 1,
        basis_kind: 'persisted_construction_artifact_review',
        review_scope: 'workspace_review_only',
        canonical_source: 'typed_preview_handoff',
        basis_provenance_label: 'artifact_backed_review_basis',
        portfolio_truth: 'imported_portfolio_snapshot',
        candidate_truth: 'hypothetical_construction_artifact',
        construction_artifact_id: 'artifact-123',
        preview_handoff: {
          handoff_kind: 'construction_artifact_preview_handoff_v1',
          construction_artifact_id: 'artifact-123',
          effective_replay_params: {
            benchmark_symbol: 'SPY',
            start_date: '2024-01-01',
            end_date: '2024-12-31',
            initial_capital: 100000,
            rebalance_frequency: 'monthly',
            base_currency: 'USD',
            commission_bps: 0,
            slippage_bps: 0,
            drift_tolerance_pct: null,
            price_basis: 'adjusted_close',
            execution_price_field: 'close',
            execution_lag_days: 1,
            symbol_overrides: {},
          },
        },
        launch_context: {
          construction_artifact_id: 'artifact-123',
          ranked_universe_artifact_id: 'ranked-1',
          ranked_universe_artifact_schema_version: 'etf_ranking_artifact_v1',
          ranking_id: 'ranking-1',
          ranking_methodology_id: 'method-1',
          ranking_as_of_date: '2026-04-23',
          current_portfolio_artifact_id: 'portfolio-1',
          current_portfolio_as_of_timestamp: '2026-04-23T09:30:00Z',
          policy_id: 'policy-1',
          policy_definition_id: 'policy-def-1',
          top_n: 2,
        },
        benchmark_symbol: 'SPY',
        base_currency: 'USD',
        replay_window: { start_date: '2024-01-01', end_date: '2024-12-31' },
        baseline_weights: [{ symbol: 'AAPL', target_weight: 0.6 }],
        candidate_weights: [{ symbol: 'MSFT', target_weight: 0.6 }],
      },
      effective_replay_params: {
        benchmark_symbol: 'SPY',
        start_date: '2024-01-01',
        end_date: '2024-12-31',
        initial_capital: 100000,
        rebalance_frequency: 'monthly',
        base_currency: 'USD',
        commission_bps: 0,
        slippage_bps: 0,
        drift_tolerance_pct: null,
        price_basis: 'adjusted_close',
        execution_price_field: 'close',
        execution_lag_days: 1,
        symbol_overrides: {},
      },
      replay: {
        methodology: 'm',
        investor_economics_status: { status: 'available', reason: null },
        reference_result: {
          portfolio_name: 'Reference',
          benchmark_symbol: 'SPY',
          start_date: '2024-01-01',
          end_date: '2024-12-31',
          observation_count: 1,
          rebalance_frequency: 'monthly',
          commission_bps: 0,
          slippage_bps: 0,
          drift_tolerance_pct: null,
          assumptions: {
            price_basis: 'adjusted_close',
            execution_price_field: 'close',
            execution_lag_days: 1,
            calendar_policy: 'intersection_common_dates',
            fractional_shares: true,
            long_only: true,
            leverage_allowed: false,
            tax_treatment: 'pre_tax',
            investor_base_currency: 'USD',
          },
          status: 'ok',
          investor_economics_status: { status: 'available', reason: null },
          instrument_metadata: [],
          starting_weights: [],
          ending_weights: [],
          metrics: {
            total_return_pct: 0,
            annualized_return_pct: 0,
            annualized_volatility_pct: 0,
            downside_volatility_pct: 0,
            max_drawdown_pct: 0,
            sharpe_ratio: 0,
            sortino_ratio: 0,
            benchmark_return_pct: 0,
            excess_return_pct: 0,
            tracking_error_pct: 0,
            information_ratio: 0,
            beta_vs_benchmark: 0,
            correlation_vs_benchmark: 0,
            total_turnover_pct: 0,
            turnover_events_count: 0,
            total_cost_paid: 0,
          },
          equity_curve: [],
          rebalance_events: [],
          trades: [],
        },
        candidate_result: {
          portfolio_name: 'Candidate',
          benchmark_symbol: 'SPY',
          start_date: '2024-01-01',
          end_date: '2024-12-31',
          observation_count: 1,
          rebalance_frequency: 'monthly',
          commission_bps: 0,
          slippage_bps: 0,
          drift_tolerance_pct: null,
          assumptions: {
            price_basis: 'adjusted_close',
            execution_price_field: 'close',
            execution_lag_days: 1,
            calendar_policy: 'intersection_common_dates',
            fractional_shares: true,
            long_only: true,
            leverage_allowed: false,
            tax_treatment: 'pre_tax',
            investor_base_currency: 'USD',
          },
          status: 'ok',
          investor_economics_status: { status: 'available', reason: null },
          instrument_metadata: [],
          starting_weights: [],
          ending_weights: [],
          metrics: {
            total_return_pct: 0,
            annualized_return_pct: 0,
            annualized_volatility_pct: 0,
            downside_volatility_pct: 0,
            max_drawdown_pct: 0,
            sharpe_ratio: 0,
            sortino_ratio: 0,
            benchmark_return_pct: 0,
            excess_return_pct: 0,
            tracking_error_pct: 0,
            information_ratio: 0,
            beta_vs_benchmark: 0,
            correlation_vs_benchmark: 0,
            total_turnover_pct: 0,
            turnover_events_count: 0,
            total_cost_paid: 0,
          },
          equity_curve: [],
          rebalance_events: [],
          trades: [],
        },
        comparison: {
          total_return_diff_pct: 0,
          annualized_return_diff_pct: 0,
          benchmark_return_diff_pct: 0,
          annualized_volatility_diff_pct: 0,
          downside_volatility_diff_pct: 0,
          max_drawdown_diff_pct: 0,
          sharpe_diff: 0,
          sortino_diff: 0,
          excess_return_diff_pct: 0,
          tracking_error_diff_pct: 0,
          information_ratio_diff: 0,
          beta_diff: 0,
          correlation_diff: 0,
          total_turnover_diff_pct: 0,
          total_cost_diff: 0,
        },
        reference_diagnostics: null,
        candidate_diagnostics: null,
        diagnostics_comparison: null,
      },
    } satisfies ConstructionArtifactReplayResponse

    expect(response.replay_provenance.turnover_diagnostics_v1?.symbol_contributions).toEqual([
      {
        symbol: 'AAPL',
        action: 'hold',
        current_weight: 0.5,
        target_weight: 0.5,
        delta_weight: 0,
        absolute_delta_weight: 0,
        turnover_contribution_weight: 0,
        contribution_fraction_of_reported_turnover: 0,
        included_in_reported_turnover: false,
      },
      {
        symbol: 'MSFT',
        action: 'initiate',
        current_weight: 0,
        target_weight: 0.4,
        delta_weight: 0.4,
        absolute_delta_weight: 0.4,
        turnover_contribution_weight: 0.2,
        contribution_fraction_of_reported_turnover: 1,
        included_in_reported_turnover: true,
      },
    ])
    expect(response.replay_provenance.hard_constraints.max_trade_intent_count).toBe(2)
  })
})

describe('MonitorDefinitionAlertReviewTimelineResponse contract', () => {
  it('keeps observation, history, and benchmark or portfolio fields distinct without methodology prose drift', () => {
    const payload: MonitorDefinitionAlertReviewTimelineResponse = {
      items: [
        {
          monitor_definition_id: 'monitor_definition_abc12345def67890',
          monitor_definition_fingerprint: 'f'.repeat(64),
          monitor_definition_schema_version: 'monitor_definition_artifact_v1',
          observation_id: 'monitor_definition_observation_abc12345',
          monitor_id: 'benchmark_trend_overlay_v1',
          benchmark_symbol: 'SPY',
          review_scope: 'current_portfolio_truth_only',
          evaluation_mode: 'review_only_observation_evaluation',
          evaluated_at: '2026-04-21T09:30:00Z',
          observation_status: 'degraded',
          cause_code: 'benchmark_observation_unconfirmed',
          alert_classification: 'degraded',
          hysteresis_transition: 'open',
          recency_status: 'recent',
          reason: 'benchmark observation is unconfirmed',
          open_handoff: {
            handoff_kind: 'monitor_definition_observation_open_handoff_v1',
            monitor_definition_id: 'monitor_definition_abc12345def67890',
            observation_id: 'monitor_definition_observation_abc12345',
            monitor_id: 'benchmark_trend_overlay_v1',
            benchmark_symbol: 'SPY',
          },
          event_kind: 'latest_observation_event',
          event_semantics: 'observation_rooted',
          thresholds: {
            minimum_confirmation_count: 2,
            risk_on_min_risky_weight: 0.95,
            risk_on_max_cash_weight: 0.05,
            risk_reduced_max_risky_weight: 0.35,
            risk_reduced_min_cash_weight: 0.65,
          },
          benchmark_observation: {
            overlay_id: 'benchmark_trend_overlay_v1',
            status: 'unconfirmed',
            as_of_month_end: '2024-12-31',
            benchmark_symbol: 'SPY',
            signal_basis: '10_month_sma_month_end',
            confirmation_count: 1,
            rule_version: 'v1',
            source_lineage: {
              source_kind: 'benchmark_overlay_signal',
              source_id: 'overlay-signal-2024-12-31',
              observed_at: '2025-01-02T09:30:00Z',
            },
          },
          portfolio_observation: {
            total_portfolio_value: 600,
            risky_value: 100,
            cash_value: 500,
            risky_weight: 0.16666667,
            cash_weight: 0.83333333,
            position_count: 2,
            source_lineage: {
              truth_basis: 'imported_portfolio_snapshot',
              importer: 'interactive_brokers',
              imported_at: '2024-04-15T09:30:00Z',
              statement_period: '2024-04',
              source_paths: ['IB2024.pdf'],
            },
          },
          active_observation: {
            required_overlay_status: 'unconfirmed',
            threshold_evaluation_performed: false,
            required_min_risky_weight: null,
            required_max_risky_weight: null,
            required_min_cash_weight: null,
            required_max_cash_weight: null,
            actual_risky_weight: null,
            actual_cash_weight: null,
            risky_weight_gap: null,
            cash_weight_gap: null,
            triggered_thresholds: [],
          },
          metadata: {
            metadata_truth: 'authoritative_persisted_artifact_metadata',
            row_provenance: 'persisted_monitor_definition_observation_artifact',
          },
        },
      ],
      metadata: {
        contract_version: 'monitor_definition_alert_review_timeline_v1',
        provenance: 'canonical_latest_observation_artifact_and_append_only_evaluation_history_entries',
        ordering: 'newest_first_evaluated_at_then_observation_event_then_history_entry_id',
        monitor_definition_id: 'monitor_definition_abc12345def67890',
        monitor_definition_fingerprint: 'f'.repeat(64),
        monitor_definition_schema_version: 'monitor_definition_artifact_v1',
        observation_row_provenance: 'persisted_monitor_definition_observation_artifact',
        history_row_provenance: 'persisted_monitor_definition_evaluation_history_entry',
        source_precedence: 'persisted_observation_artifact_then_persisted_evaluation_history_entries_then_persisted_latest_alert_episode_projection',
        latest_alert_episode: {
          contract_version: 'monitor_definition_alert_episode_v1',
          monitor_definition_id: 'monitor_definition_abc12345def67890',
          episode_id: 'monitor_definition_alert_episode_abc12345def67890',
          episode_status: 'active',
          started_at: '2026-04-21T09:30:00Z',
          ended_at: null,
          hysteresis_transition: 'open',
          source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
          latest_contributing_observation: {
            observation_id: 'monitor_definition_observation_abc12345',
            evaluated_at: '2026-04-21T09:30:00Z',
            observation_status: 'degraded',
            cause_code: 'benchmark_observation_unconfirmed',
            alert_classification: 'degraded',
          },
          recovery_basis: null,
        },
        total_rows: 1,
        observation_rows: 1,
        history_rows: 0,
      },
    }

    expect(payload.items[0].event_semantics).toBe('observation_rooted')
    expect(payload.items[0].benchmark_observation?.benchmark_symbol).toBe('SPY')
    expect(payload.items[0].portfolio_observation?.source_lineage.truth_basis).toBe('imported_portfolio_snapshot')
    expect(payload.items[0].active_observation?.required_overlay_status).toBe('unconfirmed')
    expect(payload.items[0].reason).toBe('benchmark observation is unconfirmed')
    expect(payload.metadata.latest_alert_episode?.episode_status).toBe('active')
    expect(payload.metadata.observation_row_provenance).toBe('persisted_monitor_definition_observation_artifact')
    expect(payload.metadata.history_row_provenance).toBe('persisted_monitor_definition_evaluation_history_entry')
  })

  it('narrows benchmark-trend and data-quality timeline rows by family fields', () => {
    const evidence = {
      coverage_total_count: 4,
      coverage_available_count: 3,
      coverage_missing_count: 1,
      coverage_ratio: 0.75,
      stale_symbols: ['MSFT'],
      missing_symbols: ['CASH'],
      trust_statuses: { prices: 'degraded' as const },
      withheld_inputs: [],
      unavailable_inputs: ['cash_fx_rate'],
      source_lineage: [{ source_kind: 'market_data_cache' as const, source_id: 'cache', observed_at: '2026-04-21T09:30:00Z' }],
    }
    const dataQualityObservation = {
      monitor_definition_id: 'monitor_definition_data_quality_abc12345',
      monitor_definition_fingerprint: 'd'.repeat(64),
      monitor_definition_schema_version: 'monitor_definition_artifact_v1',
      observation_id: 'monitor_definition_observation_data_quality',
      monitor_id: 'data_quality_monitor_v1',
      benchmark_symbol: 'DATA_QUALITY',
      review_scope: 'current_portfolio_truth_only',
      evaluation_mode: 'review_only_observation_evaluation',
      evaluated_at: '2026-04-21T09:30:00Z',
      observation_status: 'degraded',
      cause_code: 'market_data_coverage_degraded',
      alert_classification: 'degraded',
      hysteresis_transition: 'open',
      recency_status: 'recent',
      reason: 'input reliability evidence is degraded',
      open_handoff: { handoff_kind: 'monitor_definition_observation_open_handoff_v1', monitor_definition_id: 'monitor_definition_data_quality_abc12345', observation_id: 'monitor_definition_observation_data_quality', monitor_id: 'data_quality_monitor_v1', benchmark_symbol: 'DATA_QUALITY' },
      event_kind: 'latest_observation_event',
      event_semantics: 'observation_rooted',
      thresholds: { minimum_coverage_ratio: 0.9, max_stale_age_days: 3, required_trust_floor: 'degraded', provenance_requirements: ['cache_lineage'] },
      benchmark_observation: null,
      portfolio_observation: null,
      active_observation: null,
      data_quality_evidence: evidence,
      metadata: { metadata_truth: 'authoritative_persisted_artifact_metadata', row_provenance: 'persisted_monitor_definition_observation_artifact' },
    } satisfies MonitorDefinitionAlertReviewTimelineObservationRow
    const dataQualityHistory = {
      ...dataQualityObservation,
      history_entry_id: 'monitor_definition_history_entry_data_quality',
      outcome_status: 'degraded',
      significance_status: 'degraded',
      review_support_status: 'review_supported',
      latest_for_monitor_definition: true,
      review_handoff: { handoff_kind: 'monitor_definition_evaluation_history_review_handoff_v1', monitor_definition_id: 'monitor_definition_data_quality_abc12345', history_entry_id: 'monitor_definition_history_entry_data_quality', monitor_id: 'data_quality_monitor_v1', benchmark_symbol: 'DATA_QUALITY' },
      event_kind: 'evaluation_history_event',
      event_semantics: 'history_entry_rooted',
      metadata: { metadata_truth: 'authoritative_persisted_artifact_metadata', row_provenance: 'persisted_monitor_definition_evaluation_history_entry' },
    } satisfies MonitorDefinitionAlertReviewTimelineHistoryRow

    expect(isDataQualityTimelineObservationRow(dataQualityObservation)).toBe(true)
    expect(isBenchmarkTrendTimelineObservationRow(dataQualityObservation)).toBe(false)
    expect(isDataQualityTimelineHistoryRow(dataQualityHistory)).toBe(true)
    expect(isBenchmarkTrendTimelineHistoryRow(dataQualityHistory)).toBe(false)
    expect(isDataQualityTimelineObservationRow({ ...dataQualityObservation, alert_classification: 'action_required' })).toBe(false)
    expect(isDataQualityTimelineObservationRow({ ...dataQualityObservation, benchmark_symbol: 'SPY' })).toBe(false)
  })
})

describe('MonitorDefinitionRecoveredAlertReviewQueueResponse contract', () => {
  it('keeps recovered discovery semantics explicit and reopenable by authoritative timeline ids only', () => {
    const payload: MonitorDefinitionRecoveredAlertReviewQueueResponse = {
      items: [
        {
          monitor_definition_id: 'monitor_definition_abc12345def67890',
          monitor_definition_fingerprint: 'f'.repeat(64),
          monitor_definition_schema_version: 'monitor_definition_artifact_v1',
          observation_id: 'monitor_definition_observation_abc12345',
          latest_history_entry_id: 'monitor_definition_history_latest_info',
          monitor_id: 'benchmark_trend_overlay_v1',
          benchmark_symbol: 'SPY',
          review_scope: 'current_portfolio_truth_only',
          evaluation_mode: 'review_only_observation_evaluation',
          evaluated_at: '2026-04-21T09:30:00Z',
          observation_status: 'ok',
          cause_code: null,
          alert_classification: 'informational',
          hysteresis_transition: 'recover',
          recency_status: 'recent',
          reason: 'latest persisted observation recovered to informational state',
          alert_episode: {
            contract_version: 'monitor_definition_alert_episode_v1',
            monitor_definition_id: 'monitor_definition_abc12345def67890',
            episode_id: 'monitor_definition_alert_episode_abc12345def67890',
            episode_status: 'recovered',
            started_at: '2026-04-20T09:30:00Z',
            ended_at: '2026-04-21T09:30:00Z',
            hysteresis_transition: 'recover',
            source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
            latest_contributing_observation: {
              observation_id: 'monitor_definition_observation_abc12345',
              evaluated_at: '2026-04-21T09:30:00Z',
              observation_status: 'ok',
              cause_code: null,
              alert_classification: 'informational',
            },
            recovery_basis: {
              recovered_from_history_entry_id: 'monitor_definition_history_alert',
              recovered_from_evaluated_at: '2026-04-20T09:30:00Z',
              recovered_from_outcome_status: 'threshold_breach',
              recovered_from_cause_code: null,
              recovered_from_significance_status: 'action_required',
            },
          },
          recovered_from: {
            history_entry_id: 'monitor_definition_history_alert',
            evaluated_at: '2026-04-20T09:30:00Z',
            outcome_status: 'threshold_breach',
            cause_code: null,
            significance_status: 'action_required',
            reason: 'prior persisted alert state',
          },
          timeline_handoff: {
            handoff_kind: 'monitor_definition_alert_review_timeline_open_handoff_v1',
            monitor_definition_id: 'monitor_definition_abc12345def67890',
            selected_event_kind: 'latest_observation_event',
            observation_id: 'monitor_definition_observation_abc12345',
            monitor_id: 'benchmark_trend_overlay_v1',
            benchmark_symbol: 'SPY',
          },
          metadata: {
            metadata_truth: 'authoritative_persisted_artifact_metadata',
            row_provenance: 'persisted_monitor_definition_observation_artifact_with_latest_snapshot_and_prior_alert_history_lineage',
          },
        },
      ],
      metadata: {
        contract_version: 'monitor_definition_recovered_alert_review_queue_v1',
        provenance: 'persisted_latest_observation_with_latest_snapshot_and_prior_alert_history_lineage',
        row_provenance: 'persisted_monitor_definition_observation_artifact_with_latest_snapshot_and_prior_alert_history_lineage',
        source_precedence: 'persisted_observation_artifact_then_persisted_latest_evaluation_snapshot_then_persisted_latest_history_entry_then_prior_alert_history_entries',
        ordering: 'newest_first_evaluated_at_then_monitor_definition_id_then_observation_id',
        returned_limit: 20,
        total_queue_rows: 1,
      },
    }

    expect(payload.items[0]?.alert_classification).toBe('informational')
    expect(payload.items[0]?.alert_episode.episode_status).toBe('recovered')
    expect(payload.items[0]?.recovered_from.significance_status).toBe('action_required')
    expect(payload.items[0]?.timeline_handoff.selected_event_kind).toBe('latest_observation_event')
  })
})

describe('MonitorDefinitionAlertEpisodeHistoryResponse contract', () => {
  it('accepts the backend-shipped active alert episode inbox response shape', () => {
    const payload: MonitorDefinitionActiveAlertEpisodeInboxResponse = {
      items: [
        {
          review_scope: 'current_portfolio_truth_only',
          evaluation_mode: 'review_only_observation_evaluation',
          alert_episode: {
            schema_version: 'monitor_definition_alert_episode_record_v1',
            episode_id: 'monitor_definition_alert_episode_latest',
            monitor_definition_id: 'monitor_definition_abc12345def67890',
            monitor_definition_fingerprint: 'f'.repeat(64),
            monitor_definition_schema_version: 'monitor_definition_artifact_v1',
            monitor_id: 'benchmark_trend_overlay_v1',
            benchmark_symbol: 'SPY',
            lifecycle_status: 'open',
            latest_for_monitor_definition: true,
            started_at: '2026-04-20T09:30:00Z',
            ended_at: null,
            latest_event_at: '2026-04-21T09:30:00Z',
            hysteresis_transition: 'remain_open',
            source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
            latest_contributing_observation: {
              observation_id: 'monitor_definition_observation_abc12345',
              evaluated_at: '2026-04-21T09:30:00Z',
              observation_status: 'threshold_breach',
              cause_code: null,
              alert_classification: 'action_required',
            },
            recovery_basis: null,
            terminal_history_entry_id: 'monitor_definition_history_entry_latest_alert',
            timeline_handoff: {
              handoff_kind: 'monitor_definition_alert_episode_history_timeline_handoff_v1',
              monitor_definition_id: 'monitor_definition_abc12345def67890',
              selected_event_kind: 'latest_observation_event',
              observation_id: 'monitor_definition_observation_abc12345',
              history_entry_id: null,
              monitor_id: 'benchmark_trend_overlay_v1',
              benchmark_symbol: 'SPY',
            },
            metadata: {
              history_truth: 'authoritative_persisted_monitor_definition_alert_episode_history',
              row_provenance: 'persisted_monitor_definition_alert_episode_record',
            },
          },
          metadata: {
            metadata_truth: 'authoritative_persisted_artifact_metadata',
            row_provenance: 'persisted_monitor_definition_alert_episode_record',
          },
        },
      ],
      metadata: {
        contract_version: 'monitor_definition_active_alert_episode_inbox_v1',
        provenance: 'authoritative_persisted_monitor_definition_alert_episode_records_only',
        row_provenance: 'persisted_monitor_definition_alert_episode_record',
        source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
        ordering: 'newest_first_latest_event_at_then_monitor_definition_id_then_episode_id',
        windowing: 'before_episode_id_exclusive',
        returned_limit: 20,
        requested_before_episode_id: null,
        next_before_episode_id: null,
        total_active_episodes: 1,
      },
    }

    expect(payload.items[0]?.alert_episode.lifecycle_status).toBe('open')
    expect(payload.items[0]?.alert_episode.timeline_handoff.selected_event_kind).toBe('latest_observation_event')
    expect(payload.metadata.total_active_episodes).toBe(1)
  })

  it('keeps ordering, windowing, lifecycle labels, and drill-in handoffs explicit', () => {
    const payload: MonitorDefinitionAlertEpisodeHistoryResponse = {
      items: [
        {
          schema_version: 'monitor_definition_alert_episode_record_v1',
          episode_id: 'monitor_definition_alert_episode_latest',
          monitor_definition_id: 'monitor_definition_abc12345def67890',
          monitor_definition_fingerprint: 'f'.repeat(64),
          monitor_definition_schema_version: 'monitor_definition_artifact_v1',
          monitor_id: 'benchmark_trend_overlay_v1',
          benchmark_symbol: 'SPY',
          lifecycle_status: 'recovered',
          latest_for_monitor_definition: true,
          started_at: '2026-04-20T09:30:00Z',
          ended_at: '2026-04-21T09:30:00Z',
          latest_event_at: '2026-04-21T09:30:00Z',
          hysteresis_transition: 'recover',
          source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
          latest_contributing_observation: {
            observation_id: 'monitor_definition_observation_abc12345',
            evaluated_at: '2026-04-21T09:30:00Z',
            observation_status: 'ok',
            cause_code: null,
            alert_classification: 'informational',
          },
          recovery_basis: {
            recovered_from_history_entry_id: 'monitor_definition_history_entry_abc12345',
            recovered_from_evaluated_at: '2026-04-20T09:30:00Z',
            recovered_from_outcome_status: 'threshold_breach',
            recovered_from_cause_code: null,
            recovered_from_significance_status: 'action_required',
          },
          terminal_history_entry_id: 'monitor_definition_history_entry_latest_info',
          timeline_handoff: {
            handoff_kind: 'monitor_definition_alert_episode_history_timeline_handoff_v1',
            monitor_definition_id: 'monitor_definition_abc12345def67890',
            selected_event_kind: 'latest_observation_event',
            observation_id: 'monitor_definition_observation_abc12345',
            history_entry_id: null,
            monitor_id: 'benchmark_trend_overlay_v1',
            benchmark_symbol: 'SPY',
          },
          metadata: {
            history_truth: 'authoritative_persisted_monitor_definition_alert_episode_history',
            row_provenance: 'persisted_monitor_definition_alert_episode_record',
          },
        },
      ],
      metadata: {
        contract_version: 'monitor_definition_alert_episode_history_v1',
        history_truth: 'authoritative_persisted_monitor_definition_alert_episode_history',
        row_provenance: 'persisted_monitor_definition_alert_episode_record',
        source_precedence: 'persisted_alert_episode_record_then_canonical_evaluation_lineage_validation',
        ordering: 'newest_first_latest_event_at_then_episode_id',
        windowing: 'before_episode_id_exclusive',
        monitor_definition_id: 'monitor_definition_abc12345def67890',
        monitor_definition_fingerprint: 'f'.repeat(64),
        monitor_definition_schema_version: 'monitor_definition_artifact_v1',
        returned_limit: 20,
        requested_before_episode_id: null,
        next_before_episode_id: null,
        total_episodes: 1,
      },
    }

    expect(payload.metadata.ordering).toBe('newest_first_latest_event_at_then_episode_id')
    expect(payload.metadata.windowing).toBe('before_episode_id_exclusive')
    expect(payload.items[0]?.lifecycle_status).toBe('recovered')
    expect(payload.items[0]?.timeline_handoff.selected_event_kind).toBe('latest_observation_event')
  })
})
