"""Frozen / recording market-data providers for the dashboard golden pipeline.

The dashboard goldens (`apps/desktop/src/test/dashboardGoldens.ts`) are
generated by `export_dashboard_goldens.py`, which drives
`run_imported_dashboard_history`. That engine pulls benchmark + per-symbol
price history from a live `MarketDataService` (FMP/Yahoo cache). Live data
varies by machine and over time (adjusted-close re-adjustment after dividends/
splits), so the generated goldens churned per machine and the freshness check
needed a warm cache or `SKIP_GOLDEN_FRESHNESS_CHECK=1`.

This module severs that coupling:

- ``FrozenMarketData`` replays a committed JSON fixture
  (``golden_market_data.json``) and duck-types the four ``MarketDataService``
  methods the golden path consumes. It **raises** (never silently returns
  ``[]``) for a symbol/window absent from the fixture, so a stale fixture is a
  loud test failure rather than a wrong "unavailable" golden.
- ``RecordingMarketData`` wraps a real ``MarketDataService`` and records the
  exact four-method outputs while the generator runs, so the fixture can be
  (re)captured with ``export_dashboard_goldens.py --capture``.

Only the dashboard-golden generation path uses these. Production routes/services
still construct a live ``MarketDataService``.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from app.core.symbols import canonicalize_symbol


GOLDEN_MARKET_DATA_PATH = Path(__file__).resolve().parent / "golden_market_data.json"


class FrozenMarketDataMiss(KeyError):
    """Raised when the frozen fixture has no series for a requested
    (symbol, from_date, to_date). Signals the fixture is stale relative to the
    committed statements and must be re-captured — never papered over with an
    empty result (which would look like a legitimate 'unavailable' golden)."""


def _series_key(symbol: str, from_date: str, to_date: str) -> tuple[str, str, str]:
    return (canonicalize_symbol(symbol), from_date, to_date)


class FrozenMarketData:
    """Replays committed price series + fetch-meta. Duck-types the
    ``MarketDataService`` methods the golden generation path calls."""

    def __init__(self, payload: dict[str, Any]) -> None:
        self._series: dict[tuple[str, str, str], list[dict]] = {
            _series_key(entry["symbol"], entry["from"], entry["to"]): entry["rows"]
            for entry in payload.get("series", [])
        }
        self._meta_by_symbol: dict[str, dict] = {
            canonicalize_symbol(symbol): meta
            for symbol, meta in payload.get("fetch_meta", {}).items()
        }
        # Mirrors MarketDataService's side-effect surface: row fetches populate
        # last_fetch_meta, which the engine later reads via get_last_fetch_meta.
        self.last_fetch_meta: dict[str, dict] = {}

    @classmethod
    def from_file(cls, path: Path | None = None) -> "FrozenMarketData":
        source = path or GOLDEN_MARKET_DATA_PATH
        if not source.exists():
            raise FileNotFoundError(
                f"Frozen golden market-data fixture is missing: {source}\n"
                "Re-capture it with `python -m app.scripts.export_dashboard_goldens --capture`."
            )
        return cls(json.loads(source.read_text(encoding="utf-8")))

    def _lookup(self, symbol: str, from_date: str, to_date: str) -> list[dict]:
        key = _series_key(symbol, from_date, to_date)
        if key not in self._series:
            raise FrozenMarketDataMiss(
                f"No frozen series for {key}. The committed statements likely "
                "changed; re-capture with "
                "`python -m app.scripts.export_dashboard_goldens --capture`."
            )
        # Return defensive copies so a caller mutating rows can't corrupt the
        # in-memory fixture for a later statement in the same run.
        return [dict(row) for row in self._series[key]]

    def _record_meta(self, symbol: str) -> None:
        canonical = canonicalize_symbol(symbol)
        meta = self._meta_by_symbol.get(canonical)
        if meta is not None:
            self.last_fetch_meta[canonical] = meta

    def get_historical_prices(
        self,
        symbol: str,
        from_date: str,
        to_date: str,
        symbol_overrides: dict[str, list[str]] | None = None,
        *,
        allow_proxy_fallback: bool = False,
    ) -> list[dict]:
        rows = self._lookup(symbol, from_date, to_date)
        self._record_meta(symbol)
        return rows

    def get_direct_verified_benchmark_history(
        self, symbol: str, from_date: str, to_date: str
    ) -> list[dict]:
        rows = self._lookup(symbol, from_date, to_date)
        self._record_meta(symbol)
        return rows

    def get_historical_prices_for_symbols(
        self,
        symbols: Iterable[str],
        from_date: str,
        to_date: str,
        symbol_overrides: dict[str, list[str]] | None = None,
        *,
        allow_proxy_fallback: bool = False,
    ) -> dict[str, list[dict]]:
        return {
            canonicalize_symbol(symbol): self._lookup(symbol, from_date, to_date)
            for symbol in sorted({symbol for symbol in symbols if symbol})
        }

    def get_last_fetch_meta(self, symbol: str) -> dict | None:
        return self.last_fetch_meta.get(canonicalize_symbol(symbol))


class RecordingMarketData:
    """Wraps a real market-data service, recording the four golden-path methods'
    outputs for later freezing. Delegates everything to the inner service."""

    def __init__(self, inner: Any) -> None:
        self._inner = inner
        self._series: dict[tuple[str, str, str], list[dict]] = {}
        self._meta: dict[str, dict] = {}

    def get_historical_prices(
        self,
        symbol: str,
        from_date: str,
        to_date: str,
        symbol_overrides: dict[str, list[str]] | None = None,
        *,
        allow_proxy_fallback: bool = False,
    ) -> list[dict]:
        rows = self._inner.get_historical_prices(
            symbol, from_date, to_date, symbol_overrides, allow_proxy_fallback=allow_proxy_fallback
        )
        self._series[_series_key(symbol, from_date, to_date)] = rows
        self._capture_meta(symbol)
        return rows

    def get_direct_verified_benchmark_history(
        self, symbol: str, from_date: str, to_date: str
    ) -> list[dict]:
        rows = self._inner.get_direct_verified_benchmark_history(symbol, from_date, to_date)
        self._series[_series_key(symbol, from_date, to_date)] = rows
        self._capture_meta(symbol)
        return rows

    def get_historical_prices_for_symbols(
        self,
        symbols: Iterable[str],
        from_date: str,
        to_date: str,
        symbol_overrides: dict[str, list[str]] | None = None,
        *,
        allow_proxy_fallback: bool = False,
    ) -> dict[str, list[dict]]:
        histories = self._inner.get_historical_prices_for_symbols(
            symbols, from_date, to_date, symbol_overrides, allow_proxy_fallback=allow_proxy_fallback
        )
        for symbol, rows in histories.items():
            self._series[_series_key(symbol, from_date, to_date)] = rows
        return histories

    def get_last_fetch_meta(self, symbol: str) -> dict | None:
        meta = self._inner.get_last_fetch_meta(symbol)
        if meta is not None:
            self._meta[canonicalize_symbol(symbol)] = meta
        return meta

    def _capture_meta(self, symbol: str) -> None:
        meta = self._inner.get_last_fetch_meta(canonicalize_symbol(symbol))
        if meta is not None:
            self._meta[canonicalize_symbol(symbol)] = meta

    def to_payload(self) -> dict[str, Any]:
        return {
            "series": [
                {"symbol": symbol, "from": from_date, "to": to_date, "rows": rows}
                for (symbol, from_date, to_date), rows in sorted(self._series.items())
            ],
            "fetch_meta": {symbol: self._meta[symbol] for symbol in sorted(self._meta)},
        }
