from __future__ import annotations

import datetime
import hashlib
import math
import os
import re
from pathlib import Path
from unittest.mock import MagicMock

import pytest


# ---------------------------------------------------------------------------
# Dashboard-goldens freshness check
# ---------------------------------------------------------------------------
#
# `apps/desktop/src/test/dashboardGoldens.ts` is generated by
# `python -m app.scripts.export_dashboard_goldens` and consumed by frontend
# vitest specs. If the goldens drift from current backend output, dozens of
# tests fail with confusing assertion errors. This fixture fails fast with an
# actionable message if the committed file is out of date.
#
# Since US-21.4 the generator reads a committed, frozen market-data fixture
# (`app/scripts/golden_market_data.json`) instead of the live FMP cache, so
# `render_dashboard_goldens_text()` is fully deterministic and network-free —
# this check passes under the default network guard with no env vars and no
# warm cache (the per-machine churn that plagued Epics 16–20 is gone). Goldens
# only change when a formula/schema/fixture changes; re-capture market data
# (rare — only when the committed statements change) with
# `python -m app.scripts.export_dashboard_goldens --capture`.
#
# `SKIP_GOLDEN_FRESHNESS_CHECK=1` remains as an explicit escape hatch for narrow
# runs that don't touch the dashboard surface; it is no longer required for a
# clean bare-`pytest` run.
#
# The check normalizes `source_path` strings before comparing so the check
# tolerates running pytest from a git worktree whose absolute path differs
# from the primary checkout. Real content drift (formula changes, schema
# changes, fixture changes) still fails fast.


_GOLDENS_SOURCE_PATH_RE = re.compile(r'"source_path": "[^"]*"')


def _strip_source_paths(text: str) -> str:
    return _GOLDENS_SOURCE_PATH_RE.sub('"source_path": "<normalized>"', text)


@pytest.fixture(scope="session", autouse=True)
def _check_dashboard_goldens_freshness() -> None:
    if os.environ.get("SKIP_GOLDEN_FRESHNESS_CHECK") == "1":
        return

    from app.scripts.export_dashboard_goldens import (
        _dashboard_golden_output_path,
        _repo_root,
        render_dashboard_goldens_text,
    )

    repo_root = _repo_root()
    committed_path: Path = _dashboard_golden_output_path(repo_root)

    if not committed_path.exists():
        pytest.fail(
            f"Dashboard goldens file is missing: {committed_path}\n"
            "Run `python scripts/run_all_tests.py` or "
            "`python -m app.scripts.export_dashboard_goldens` to generate it.",
            pytrace=False,
        )

    try:
        fresh_text = render_dashboard_goldens_text(repo_root)
    except Exception as exc:  # pragma: no cover - protective wrapper
        pytest.fail(
            "Dashboard goldens freshness check could not regenerate goldens: "
            f"{exc!r}\nSet SKIP_GOLDEN_FRESHNESS_CHECK=1 to bypass.",
            pytrace=False,
        )

    committed_text = committed_path.read_text(encoding="utf-8")

    if _strip_source_paths(fresh_text) != _strip_source_paths(committed_text):
        pytest.fail(
            "Dashboard goldens are stale: backend output differs from "
            f"{committed_path.relative_to(repo_root)}.\n"
            "Run `python scripts/run_all_tests.py` (canonical) or "
            "`python -m app.scripts.export_dashboard_goldens` to regenerate, "
            "review the diff, and commit it.\n"
            "Set SKIP_GOLDEN_FRESHNESS_CHECK=1 to bypass for a narrow run.",
            pytrace=False,
        )


# ---------------------------------------------------------------------------
# Helpers for generating deterministic synthetic price rows
# ---------------------------------------------------------------------------

_MOCK_HOLIDAYS: frozenset[str] = frozenset({
    "2025-01-20",  # MLK Day 2025
    "2025-02-17",  # Presidents Day 2025
    "2025-04-18",  # Good Friday 2025
    "2025-05-26",  # Memorial Day 2025
    "2025-06-19",  # Juneteenth 2025
    "2025-07-04",  # Independence Day 2025
    "2025-09-01",  # Labor Day 2025
    "2025-11-27",  # Thanksgiving 2025
    "2025-12-25",  # Christmas 2025
    "2026-01-01",  # New Year's 2026
    "2026-01-19",  # MLK Day 2026
    "2026-02-16",  # Presidents Day 2026
    "2026-04-03",  # Good Friday 2026
    "2026-05-25",  # Memorial Day 2026
})


def _mock_price_rows(symbol: str, from_date: str, to_date: str, *_args: object, **_kwargs: object) -> list[dict]:
    """Generate deterministic synthetic daily price rows (no adjClose) for a symbol.

    Uses a sha256-based seed per symbol so different symbols produce distinct but
    reproducible series. The daily return is small (±0.3%) to keep all plausibility
    bounds easily satisfied, and there is no adjClose so the rows are classified as
    "unverified_close_only" by detect_history_return_basis.
    """
    seed_val = int(hashlib.sha256(symbol.upper().encode()).hexdigest(), 16) % (2 ** 31)
    base_price = 100.0 + (seed_val % 400)

    start = datetime.date.fromisoformat(from_date)
    end = datetime.date.fromisoformat(to_date)
    rows: list[dict] = []
    price = base_price
    day = start
    i = 0
    while day <= end:
        if day.weekday() < 5 and day.isoformat() not in _MOCK_HOLIDAYS:
            daily_return = 0.003 * math.sin(i * 0.5 + seed_val % 1000)
            price = round(price * (1.0 + daily_return), 2)
            rows.append({"date": day.isoformat(), "price": price})
            i += 1
        day += datetime.timedelta(days=1)
    return rows


def _mock_prices_for_symbols(
    symbols: list[str],
    from_date: str,
    to_date: str,
    *_args: object,
    **_kwargs: object,
) -> dict[str, list[dict]]:
    return {sym: _mock_price_rows(sym, from_date, to_date) for sym in symbols if sym}


_SPY_MOCK_ETF_HOLDINGS: list[dict] = [
    {"asset": "AAPL", "name": "Apple Inc.", "weightPercentage": 7.0},
    {"asset": "MSFT", "name": "Microsoft Corp.", "weightPercentage": 6.5},
    {"asset": "AMZN", "name": "Amazon.com Inc.", "weightPercentage": 5.0},
    {"asset": "NVDA", "name": "NVIDIA Corp.", "weightPercentage": 4.5},
    {"asset": "GOOGL", "name": "Alphabet Inc. Class A", "weightPercentage": 3.5},
    {"asset": "META", "name": "Meta Platforms Inc.", "weightPercentage": 2.8},
    {"asset": "BRK.B", "name": "Berkshire Hathaway B", "weightPercentage": 2.5},
    {"asset": "LLY", "name": "Eli Lilly", "weightPercentage": 2.2},
    {"asset": "JPM", "name": "JPMorgan Chase", "weightPercentage": 2.0},
    {"asset": "UNH", "name": "UnitedHealth Group", "weightPercentage": 1.8},
    {"asset": "Other", "name": "Other holdings", "weightPercentage": 62.2},
]  # total weightPercentage = 100.0 → "verified"


@pytest.fixture(autouse=True)
def _clear_cache_memory() -> None:
    """Clear the process-level in-memory cache layer (US-20.3) before each test
    so the memo never leaks parsed payloads across tests — keeps the suite
    deterministic (the project's stability gate), including under xdist."""
    from app.core.cache import clear_memory_cache

    clear_memory_cache()


@pytest.fixture(autouse=True)
def _disable_yfinance_fallback(monkeypatch: pytest.MonkeyPatch) -> None:
    """Disable the yfinance secondary-provider fallback (US-18.1) by default so
    no test accidentally hits the network when FMP returns empty. The default
    yfinance client returns no rows; tests that exercise the fallback patch
    `app.services.market_data.YFinanceClient` themselves (which takes precedence).
    """
    yf_mock = MagicMock()
    yf_mock.return_value.get_historical_price_light.return_value = []
    monkeypatch.setattr("app.services.market_data.YFinanceClient", yf_mock, raising=False)


@pytest.fixture(autouse=True)
def _mock_exposure_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the exposure engine so that benchmark ETF holdings
    are available (SPY → verified, 100 % weight covered) without a live FMP connection.

    Tests that patch app.services.exposure_engine.MarketDataService themselves via
    mocker.patch take precedence over this monkeypatch.
    """

    def _make_exposure_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        # ETF holdings: SPY → verified (≥99 % weightPercentage)
        inst.get_etf_holdings.return_value = ("SPY", _SPY_MOCK_ETF_HOLDINGS)
        inst.get_etf_holdings_for_date.return_value = ("SPY", _SPY_MOCK_ETF_HOLDINGS)
        # Historical prices: return unverified (no adjClose) rows on demand
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        return mock_svc

    monkeypatch.setattr(
        "app.services.exposure_engine.MarketDataService",
        _make_exposure_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_dashboard_history_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the dashboard history engine so that benchmark
    and portfolio symbol price histories return deterministic synthetic rows
    instead of live FMP data.

    The snapshot-only route (run_dashboard_history_engine) never reaches
    MarketDataService, so this mock is harmless for those tests.  Tests that need
    specific price trajectories (e.g. the FF2026 golden test) can override via
    mocker.patch, which takes precedence over this monkeypatch.
    """

    def _make_dashboard_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_direct_verified_benchmark_history.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        inst.get_last_fetch_meta.return_value = {
            "type": "history",
            "requested_symbol": "SPY",
            "resolved_symbol": "SPY",
            "cached": True,
            "vendor": "FMP",
            "endpoint": "historical-price-eod/light",
            "direct_path_only": True,
            "fallback_used": False,
            "proxy_used": False,
            "mixed_source": False,
            "symbol_override_used": False,
        }
        return mock_svc

    monkeypatch.setattr(
        "app.services.dashboard_history_engine.MarketDataService",
        _make_dashboard_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_diagnostics_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the diagnostics engine so that benchmark and
    portfolio symbol price histories return deterministic synthetic rows instead
    of live FMP data.

    Tests that patch app.services.diagnostics_engine.MarketDataService themselves
    via mocker.patch take precedence over this monkeypatch.
    """

    def _make_diagnostics_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        return mock_svc

    monkeypatch.setattr(
        "app.services.diagnostics_engine.MarketDataService",
        _make_diagnostics_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_risk_engines_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the stress / drawdown / distribution engines so
    their "real portfolio" tests run against deterministic synthetic rows instead
    of live FMP data (US-21.1 — the suite must pass offline with no API key).

    Tests that patch an engine's MarketDataService themselves via mocker.patch
    take precedence over this monkeypatch.
    """

    def _make_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        return mock_svc

    for engine_module in (
        "app.services.stress_engine",
        "app.services.drawdown_engine",
        "app.services.distribution_engine",
    ):
        monkeypatch.setattr(f"{engine_module}.MarketDataService", _make_mock())


