from __future__ import annotations

import datetime
import hashlib
import math
import os
import re
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from unittest.mock import MagicMock

import pytest


# ---------------------------------------------------------------------------
# Dashboard-goldens freshness check
# ---------------------------------------------------------------------------
#
# `apps/desktop/src/test/dashboardGoldens.ts` is generated by
# `python -m app.scripts.export_dashboard_goldens` and consumed by frontend
# vitest specs. If the goldens drift from current backend output, dozens of
# tests fail with confusing assertion errors. The canonical entrypoint
# `scripts/run_all_tests.py` always regenerates goldens before running pytest;
# this fixture protects developers (and agents) who invoke `pytest` directly
# by failing fast with an actionable message.
#
# Set `SKIP_GOLDEN_FRESHNESS_CHECK=1` to bypass the check (e.g. when running
# narrow subsets of tests that don't touch the dashboard surface).
#
# The check normalizes `source_path` strings before comparing so the check
# tolerates running pytest from a git worktree whose absolute path differs
# from the primary checkout. Real content drift (formula changes, schema
# changes, fixture changes) still fails fast.


_GOLDENS_SOURCE_PATH_RE = re.compile(r'"source_path": "[^"]*"')


def _strip_source_paths(text: str) -> str:
    return _GOLDENS_SOURCE_PATH_RE.sub('"source_path": "<normalized>"', text)


@pytest.fixture(scope="session", autouse=True)
def _check_dashboard_goldens_freshness() -> None:
    if os.environ.get("SKIP_GOLDEN_FRESHNESS_CHECK") == "1":
        return

    from app.scripts.export_dashboard_goldens import (
        _dashboard_golden_output_path,
        _repo_root,
        render_dashboard_goldens_text,
    )

    repo_root = _repo_root()
    committed_path: Path = _dashboard_golden_output_path(repo_root)

    if not committed_path.exists():
        pytest.fail(
            f"Dashboard goldens file is missing: {committed_path}\n"
            "Run `python scripts/run_all_tests.py` or "
            "`python -m app.scripts.export_dashboard_goldens` to generate it.",
            pytrace=False,
        )

    try:
        fresh_text = render_dashboard_goldens_text(repo_root)
    except Exception as exc:  # pragma: no cover - protective wrapper
        pytest.fail(
            "Dashboard goldens freshness check could not regenerate goldens: "
            f"{exc!r}\nSet SKIP_GOLDEN_FRESHNESS_CHECK=1 to bypass.",
            pytrace=False,
        )

    committed_text = committed_path.read_text(encoding="utf-8")

    if _strip_source_paths(fresh_text) != _strip_source_paths(committed_text):
        pytest.fail(
            "Dashboard goldens are stale: backend output differs from "
            f"{committed_path.relative_to(repo_root)}.\n"
            "Run `python scripts/run_all_tests.py` (canonical) or "
            "`python -m app.scripts.export_dashboard_goldens` to regenerate, "
            "review the diff, and commit it.\n"
            "Set SKIP_GOLDEN_FRESHNESS_CHECK=1 to bypass for a narrow run.",
            pytrace=False,
        )


# ---------------------------------------------------------------------------
# Helpers for generating deterministic synthetic price rows
# ---------------------------------------------------------------------------

_MOCK_HOLIDAYS: frozenset[str] = frozenset({
    "2025-01-20",  # MLK Day 2025
    "2025-02-17",  # Presidents Day 2025
    "2025-04-18",  # Good Friday 2025
    "2025-05-26",  # Memorial Day 2025
    "2025-06-19",  # Juneteenth 2025
    "2025-07-04",  # Independence Day 2025
    "2025-09-01",  # Labor Day 2025
    "2025-11-27",  # Thanksgiving 2025
    "2025-12-25",  # Christmas 2025
    "2026-01-01",  # New Year's 2026
    "2026-01-19",  # MLK Day 2026
    "2026-02-16",  # Presidents Day 2026
    "2026-04-03",  # Good Friday 2026
    "2026-05-25",  # Memorial Day 2026
})


def _mock_price_rows(symbol: str, from_date: str, to_date: str, *_args: object, **_kwargs: object) -> list[dict]:
    """Generate deterministic synthetic daily price rows (no adjClose) for a symbol.

    Uses a sha256-based seed per symbol so different symbols produce distinct but
    reproducible series. The daily return is small (±0.3%) to keep all plausibility
    bounds easily satisfied, and there is no adjClose so the rows are classified as
    "unverified_close_only" by detect_history_return_basis.
    """
    seed_val = int(hashlib.sha256(symbol.upper().encode()).hexdigest(), 16) % (2 ** 31)
    base_price = 100.0 + (seed_val % 400)

    start = datetime.date.fromisoformat(from_date)
    end = datetime.date.fromisoformat(to_date)
    rows: list[dict] = []
    price = base_price
    day = start
    i = 0
    while day <= end:
        if day.weekday() < 5 and day.isoformat() not in _MOCK_HOLIDAYS:
            daily_return = 0.003 * math.sin(i * 0.5 + seed_val % 1000)
            price = round(price * (1.0 + daily_return), 2)
            rows.append({"date": day.isoformat(), "price": price})
            i += 1
        day += datetime.timedelta(days=1)
    return rows


def _mock_prices_for_symbols(
    symbols: list[str],
    from_date: str,
    to_date: str,
    *_args: object,
    **_kwargs: object,
) -> dict[str, list[dict]]:
    return {sym: _mock_price_rows(sym, from_date, to_date) for sym in symbols if sym}


_SPY_MOCK_ETF_HOLDINGS: list[dict] = [
    {"asset": "AAPL", "name": "Apple Inc.", "weightPercentage": 7.0},
    {"asset": "MSFT", "name": "Microsoft Corp.", "weightPercentage": 6.5},
    {"asset": "AMZN", "name": "Amazon.com Inc.", "weightPercentage": 5.0},
    {"asset": "NVDA", "name": "NVIDIA Corp.", "weightPercentage": 4.5},
    {"asset": "GOOGL", "name": "Alphabet Inc. Class A", "weightPercentage": 3.5},
    {"asset": "META", "name": "Meta Platforms Inc.", "weightPercentage": 2.8},
    {"asset": "BRK.B", "name": "Berkshire Hathaway B", "weightPercentage": 2.5},
    {"asset": "LLY", "name": "Eli Lilly", "weightPercentage": 2.2},
    {"asset": "JPM", "name": "JPMorgan Chase", "weightPercentage": 2.0},
    {"asset": "UNH", "name": "UnitedHealth Group", "weightPercentage": 1.8},
    {"asset": "Other", "name": "Other holdings", "weightPercentage": 62.2},
]  # total weightPercentage = 100.0 → "verified"


# Minimal unverified price rows for the optimizer preview service.
# These rows carry only "price" (no "adjClose"), which makes
# detect_history_return_basis return "unverified_close_only" and therefore
# return_basis_path_trust_from_evidence return "degraded_unverified_return_basis".
_UNVERIFIED_PRICE_ROWS = [
    {"date": "2024-01-02", "price": 100.0},
    {"date": "2024-06-03", "price": 103.0},
    {"date": "2024-12-31", "price": 106.0},
]


@pytest.fixture(autouse=True)
def _mock_optimizer_preview_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the optimizer preview service so that
    return-basis attestations are built with 'degraded_unverified_return_basis'
    (unverified price data) rather than 'unavailable' (no FMP data in tests).

    This fixture provides minimal raw-price rows (no adjClose) for every
    symbol requested by the preview service, giving a deterministic non-unavailable
    attestation without requiring a live FMP connection or cache.

    Tests that need a specific trust level (e.g., verified_adjusted_close) can
    patch app.services.optimizer_preview_service.MarketDataService themselves via
    mocker.patch, which takes precedence over this monkeypatch.
    """
    mock_svc = MagicMock()
    mock_svc.return_value.get_historical_prices.return_value = _UNVERIFIED_PRICE_ROWS
    mock_svc.return_value.get_historical_prices_for_symbols.return_value = {}

    monkeypatch.setattr(
        "app.services.optimizer_preview_service.MarketDataService",
        mock_svc,
    )


@pytest.fixture(autouse=True)
def _isolate_artifact_stores(
    tmp_path_factory: pytest.TempPathFactory,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Isolate every persisted-artifact store to per-test tmp directories by default.

    The cross-kind ranking catalog scans the ETF, replacement, generic ranking, and
    optimizer-handoff artifact directories alongside one another. Without per-test
    isolation, artifacts created by tests that hit the FastAPI route layer (which
    instantiates the default stores against the real settings paths) leak into
    `data/artifacts/<kind>/` and cause cross-test pollution. They also cause cross-
    kind catalog tests to see artifacts from other kinds.

    This fixture monkeypatches `get_settings` in each artifact-store module to return
    a `SimpleNamespace` whose dir fields point at isolated `tmp_path_factory`-created
    directories. Explicit per-test `mocker.patch.object(...)` still overrides the
    fixture (monkeypatch and mocker are independent), so tests that need a specific
    path keep working unchanged.

    Uses `tmp_path_factory` (NOT the test's own `tmp_path`) so the test's tmp_path
    stays empty — several tests assert that fact (e.g., persistence-failure tests).
    """
    etf_dir = tmp_path_factory.mktemp("etf-ranking-artifacts")
    replacement_dir = tmp_path_factory.mktemp("etf-replacement-ranking-artifacts")
    generic_dir = tmp_path_factory.mktemp("generic-ranking-artifacts")
    optimizer_dir = tmp_path_factory.mktemp("optimizer-handoffs")

    def _fake_etf_settings() -> Any:
        return SimpleNamespace(etf_ranking_artifact_dir=str(etf_dir))

    def _fake_replacement_settings() -> Any:
        return SimpleNamespace(replacement_ranking_artifact_dir=str(replacement_dir))

    def _fake_generic_settings() -> Any:
        return SimpleNamespace(generic_ranking_artifacts_dir=str(generic_dir))

    def _fake_optimizer_settings() -> Any:
        return SimpleNamespace(optimizer_handoff_dir=str(optimizer_dir))

    monkeypatch.setattr(
        "app.services.etf_ranking_artifact_service.get_settings",
        _fake_etf_settings,
    )
    monkeypatch.setattr(
        "app.services.replacement_ranking_artifact_service.get_settings",
        _fake_replacement_settings,
    )
    monkeypatch.setattr(
        "app.services.generic_ranking_artifact_service.get_settings",
        _fake_generic_settings,
    )
    monkeypatch.setattr(
        "app.services.optimizer_artifact_service.get_settings",
        _fake_optimizer_settings,
    )


@pytest.fixture(autouse=True)
def _mock_exposure_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the exposure engine so that benchmark ETF holdings
    are available (SPY → verified, 100 % weight covered) without a live FMP connection.

    Tests that patch app.services.exposure_engine.MarketDataService themselves via
    mocker.patch take precedence over this monkeypatch.
    """

    def _make_exposure_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        # ETF holdings: SPY → verified (≥99 % weightPercentage)
        inst.get_etf_holdings.return_value = ("SPY", _SPY_MOCK_ETF_HOLDINGS)
        inst.get_etf_holdings_for_date.return_value = ("SPY", _SPY_MOCK_ETF_HOLDINGS)
        # Historical prices: return unverified (no adjClose) rows on demand
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        return mock_svc

    monkeypatch.setattr(
        "app.services.exposure_engine.MarketDataService",
        _make_exposure_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_dashboard_history_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the dashboard history engine so that benchmark
    and portfolio symbol price histories return deterministic synthetic rows
    instead of live FMP data.

    The snapshot-only route (run_dashboard_history_engine) never reaches
    MarketDataService, so this mock is harmless for those tests.  Tests that need
    specific price trajectories (e.g. the FF2026 golden test) can override via
    mocker.patch, which takes precedence over this monkeypatch.
    """

    def _make_dashboard_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_direct_verified_benchmark_history.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        inst.get_last_fetch_meta.return_value = {
            "type": "history",
            "requested_symbol": "SPY",
            "resolved_symbol": "SPY",
            "cached": True,
            "vendor": "FMP",
            "endpoint": "historical-price-eod/light",
            "direct_path_only": True,
            "fallback_used": False,
            "proxy_used": False,
            "mixed_source": False,
            "symbol_override_used": False,
        }
        return mock_svc

    monkeypatch.setattr(
        "app.services.dashboard_history_engine.MarketDataService",
        _make_dashboard_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_diagnostics_engine_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in the diagnostics engine so that benchmark and
    portfolio symbol price histories return deterministic synthetic rows instead
    of live FMP data.

    Tests that patch app.services.diagnostics_engine.MarketDataService themselves
    via mocker.patch take precedence over this monkeypatch.
    """

    def _make_diagnostics_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        inst.get_historical_prices.side_effect = _mock_price_rows
        inst.get_historical_prices_for_symbols.side_effect = _mock_prices_for_symbols
        return mock_svc

    monkeypatch.setattr(
        "app.services.diagnostics_engine.MarketDataService",
        _make_diagnostics_mock(),
    )


@pytest.fixture(autouse=True)
def _mock_dataset_catalog_market_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock MarketDataService in DatasetCatalog so that backtest dataset-info
    lookups return 'fmp' for equities and 'proxy approximation (<proxy>)' for
    continuous futures, instead of 'local-sample' / 'local approximation'.

    Tests that patch app.datasets.catalog.MarketDataService themselves via
    mocker.patch take precedence over this monkeypatch.
    """

    def _make_catalog_mock() -> MagicMock:
        mock_svc = MagicMock()
        inst = mock_svc.return_value
        # Return non-empty rows for any symbol so has_live_history=True
        inst.get_historical_prices.side_effect = _mock_price_rows
        return mock_svc

    monkeypatch.setattr(
        "app.datasets.catalog.MarketDataService",
        _make_catalog_mock(),
    )
